// examples/sveltekit/src/routes/+page.svelte
<script>
  import PixelSnow from "$lib/PixelSnow.svelte";
  const chips = ["MDX", "Themes", "Search", "AI-ready"];
  const installCommand = "npx @farming-labs/docs init";
  let copied = false;

  async function copyCommand() {
    await navigator.clipboard.writeText(installCommand);
    copied = true;
    window.setTimeout(() => {
      copied = false;
    }, 1500);
  }
</script>

<svelte:head>
  <title>Farming Labs Docs — SvelteKit Example</title>
  <meta
    name="description"
    content="Centered landing page for the Farming Labs docs SvelteKit example."
  />
</svelte:head>

<main class="landing-shell">
  <PixelSnow />
  <section class="landing">
    <div class="landing-badge">
      <span>@farming-labs/docs</span>
      <span class="landing-framework">SvelteKit Example</span>
    </div>

    <div class="landing-copy">
      <h1>
        a documentation framework
        <br />
        that <span>just works.</span>
      </h1>
      <p>
        Framework-native docs with MDX, themes, search, page actions, and AI-ready utilities.
        This example shows the same Farming Labs docs model running on SvelteKit.
      </p>
    </div>

    <div class="landing-chips">
      {#each chips as chip}
        <span>{chip}</span>
      {/each}
    </div>

    <div class="landing-command">
      <span class="landing-command-label">Install in one command</span>
      <div class="landing-command-shell">
        <span class="landing-command-prompt">&gt;</span>
        <code class="landing-command-code">{installCommand}</code>
        <button type="button" class="landing-command-copy" on:click={copyCommand}>
          {copied ? "Copied" : "Copy"}
        </button>
      </div>
    </div>

    <div class="landing-actions">
      <a class="landing-primary" href="/docs?lang=en">Open Example Docs</a>
      <a class="landing-reference" href="https://docs.farming-labs.dev" target="_blank" rel="noreferrer">
        <span>docs.farming-labs.dev</span>
        <span class="landing-reference-arrow">↗</span>
      </a>
    </div>

    <p class="landing-note">
      // Start locally at <code>/docs?lang=en</code>, then use the full reference when you need the broader map.
    </p>
  </section>
</main>

<style>
  .landing-shell {
    min-height: 100vh;
    display: grid;
    place-items: center;
    padding: 2rem 1.25rem;
    position: relative;
    overflow: hidden;
    background: var(--color-fd-background, #0b0b0c);
  }

  .landing {
    width: 100%;
    max-width: 980px;
    text-align: center;
    display: grid;
    gap: 1.5rem;
    position: relative;
    z-index: 1;
  }

  .landing-badge {
    justify-self: center;
    display: inline-flex;
    align-items: center;
    gap: 0.75rem;
    padding: 0.5rem 0.85rem;
    border-radius: 0;
    border: 1px dashed color-mix(in srgb, var(--color-fd-border) 55%, transparent);
    background-image:
      repeating-linear-gradient(
        -45deg,
        color-mix(in srgb, var(--color-fd-border) 7%, transparent),
        color-mix(in srgb, var(--color-fd-foreground) 7%, transparent) 1px,
        transparent 1px,
        transparent 6px
      );
    font-size: 0.78rem;
    letter-spacing: 0.14em;
    font-family: var(--fd-font-mono, var(--font-geist-mono, monospace));
    text-transform: uppercase;
  }

  .landing-framework {
    opacity: 0.45;
  }

  .landing-copy {
    display: grid;
    gap: 1rem;
    justify-items: center;
  }

  .landing-copy h1 {
    margin: 0;
    max-width: 860px;
    font-size: clamp(2.8rem, 7vw, 5.6rem);
    line-height: 0.95;
    letter-spacing: -0.05em;
  }

  .landing-copy h1 span {
    display: inline-block;
    padding: 0 0.3em;
    background: var(--color-fd-foreground, #fff);
    color: var(--color-fd-background, #0b0b0c);
  }

  .landing-copy p {
    margin: 0;
    max-width: 720px;
    font-size: 1.02rem;
    line-height: 1.8;
    color: var(--color-fd-muted-foreground, rgba(255, 255, 255, 0.72));
  }

  .landing-chips {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 0.75rem;
  }

  .landing-chips span {
    border: 1px solid var(--color-fd-border, rgba(255, 255, 255, 0.12));
    border-radius: 0;
    padding: 0.45rem 0.8rem;
    font-size: 0.72rem;
    letter-spacing: 0.14em;
    font-family: var(--fd-font-mono, var(--font-geist-mono, monospace));
    text-transform: uppercase;
    opacity: 0.72;
  }

  .landing-actions {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center;
    gap: 1rem;
  }

  .landing-command {
    width: 100%;
    max-width: 544px;
    justify-self: center;
    display: grid;
    gap: 0.65rem;
  }

  .landing-command-label {
    justify-self: start;
    font-size: 0.72rem;
    letter-spacing: 0.14em;
    font-family: var(--fd-font-mono, var(--font-geist-mono, monospace));
    text-transform: uppercase;
    color: var(--color-fd-muted-foreground, rgba(255, 255, 255, 0.58));
  }

  .landing-command-shell {
    display: grid;
    grid-template-columns: auto 1fr auto;
    align-items: stretch;
    border: 1px solid var(--color-fd-border, rgba(255, 255, 255, 0.12));
    background: color-mix(in srgb, var(--color-fd-card, #111) 92%, transparent);
  }

  .landing-command-prompt {
    display: grid;
    place-items: center;
    padding: 0 1rem;
    border-right: 1px solid var(--color-fd-border, rgba(255, 255, 255, 0.12));
    font-family: var(--fd-font-mono, var(--font-geist-mono, monospace));
    font-size: 1rem;
    color: var(--color-fd-muted-foreground, rgba(255, 255, 255, 0.58));
  }

  .landing-command-code {
    display: grid;
    align-items: center;
    padding: 0.95rem 1rem;
    text-align: left;
    font-family: var(--fd-font-mono, var(--font-geist-mono, monospace));
    font-size: clamp(0.82rem, 2vw, 1rem);
    overflow-x: auto;
    white-space: nowrap;
  }

  .landing-command-copy {
    border: 0;
    border-left: 1px solid var(--color-fd-border, rgba(255, 255, 255, 0.12));
    background: transparent;
    color: inherit;
    min-width: 88px;
    padding: 0 1rem;
    cursor: pointer;
    font-family: var(--fd-font-mono, var(--font-geist-mono, monospace));
    font-size: 0.72rem;
    letter-spacing: 0.14em;
    text-transform: uppercase;
  }

  .landing-primary,
  .landing-reference {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    font-family: var(--fd-font-mono, var(--font-geist-mono, monospace));
    letter-spacing: 0.14em;
    text-transform: uppercase;
  }

  .landing-primary {
    min-width: 180px;
    padding: 0.95rem 1.35rem;
    border-radius: 0;
    text-decoration: none;
    font-weight: 600;
    font-size: 0.76rem;
    background: var(--color-fd-foreground, #fff);
    color: var(--color-fd-background, #0b0b0c);
  }

  .landing-reference {
    border-bottom: 1px dotted color-mix(in srgb, var(--color-fd-border) 55%, transparent);
    align-items: flex-end;
    color: var(--color-fd-muted-foreground, rgba(255, 255, 255, 0.58));
    gap: 0.5rem;
    height: 100%;
    padding-bottom: 0.2rem;
    text-decoration: none;
    font-size: 0.66rem;
  }

  .landing-reference:hover {
    color: var(--color-fd-foreground, rgba(255, 255, 255, 0.82));
  }

  .landing-reference-arrow {
    opacity: 0.55;
  }

  .landing-note {
    margin: 0;
    font-size: 0.82rem;
    font-family: var(--fd-font-mono, var(--font-geist-mono, monospace));
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: var(--color-fd-muted-foreground, rgba(255, 255, 255, 0.58));
  }
</style>

// examples/tanstack-start/src/routes/index.tsx
import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import PixelSnow from "@/components/pixel-snow";

const referenceHref = "https://docs.farming-labs.dev";
const installCommand = "npx @farming-labs/docs init";

export const Route = createFileRoute("/")({
  component: HomePage,
});

function HomePage() {
  const [copied, setCopied] = useState(false);

  const chipStyle: React.CSSProperties = {
    border: "1px solid var(--color-fd-border, rgba(255,255,255,0.12))",
    borderRadius: 0,
    padding: "0.45rem 0.8rem",
    fontSize: "0.72rem",
    letterSpacing: "0.14em",
    fontFamily: "var(--fd-font-mono, var(--font-geist-mono, monospace))",
    textTransform: "uppercase",
    opacity: 0.72,
  };

  const buttonBase: React.CSSProperties = {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 0,
    padding: "0.95rem 1.35rem",
    textDecoration: "none",
    fontWeight: 600,
    minWidth: 180,
    fontFamily: "var(--fd-font-mono, var(--font-geist-mono, monospace))",
    fontSize: "0.76rem",
    letterSpacing: "0.14em",
    textTransform: "uppercase",
  };

  const copyCommand = async () => {
    await navigator.clipboard.writeText(installCommand);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1500);
  };

  return (
    <main
      style={{
        minHeight: "100vh",
        position: "relative",
        display: "grid",
        placeItems: "center",
        padding: "2rem 1.25rem",
        overflow: "hidden",
        background: "var(--color-fd-background, #0b0b0c)",
      }}
    >
      <PixelSnow />
      <section
        style={{
          width: "100%",
          maxWidth: 980,
          textAlign: "center",
          display: "grid",
          gap: "1.5rem",
          position: "relative",
          zIndex: 1,
        }}
      >
        <div
          className="border border-dashed border-black/10 dark:border-white/10"
          style={{
            display: "inline-flex",
            justifySelf: "center",
            alignItems: "center",
            gap: "0.75rem",
            padding: "0.5rem 0.85rem",
            borderRadius: 0,
            backgroundImage:
              "repeating-linear-gradient(-45deg, color-mix(in srgb, var(--color-fd-border) 7%, transparent), color-mix(in srgb, var(--color-fd-foreground) 7%, transparent) 1px, transparent 1px, transparent 6px)",
            fontSize: "0.78rem",
            letterSpacing: "0.14em",
            fontFamily: "var(--fd-font-mono, var(--font-geist-mono, monospace))",
            textTransform: "uppercase",
          }}
        >
          <span>@farming-labs/docs</span>
          <span style={{ opacity: 0.45 }}>TanStack Start Example</span>
        </div>

        <div style={{ display: "grid", gap: "1rem", justifyItems: "center" }}>
          <h1
            style={{
              margin: 0,
              fontSize: "clamp(2.8rem, 7vw, 5.6rem)",
              lineHeight: 0.95,
              letterSpacing: "-0.05em",
              maxWidth: 860,
            }}
          >
            A documentation framework
            <br />
            that{" "}
            <span
              style={{
                background: "var(--color-fd-foreground, #fff)",
                color: "var(--color-fd-background, #0b0b0c)",
                padding: "0 0.3em",
                display: "inline-block",
              }}
            >
              just works.
            </span>
          </h1>

          <p
            style={{
              margin: 0,
              maxWidth: 720,
              fontSize: "1.02rem",
              lineHeight: 1.8,
              color: "var(--color-fd-muted-foreground, rgba(255,255,255,0.72))",
            }}
          >
            Framework-native docs with MDX, themes, search, page actions, and AI-ready utilities.
            This example shows the same Farming Labs docs model running on TanStack Start.
          </p>
        </div>

        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            justifyContent: "center",
            gap: "0.75rem",
          }}
        >
          <span style={chipStyle}>MDX</span>
          <span style={chipStyle}>Themes</span>
          <span style={chipStyle}>Search</span>
          <span style={chipStyle}>AI-ready</span>
        </div>

        <div
          style={{
            width: "100%",
            maxWidth: 544,
            justifySelf: "center",
            display: "grid",
            gap: "0.65rem",
          }}
        >
          <span
            style={{
              justifySelf: "start",
              fontFamily: "var(--fd-font-mono, var(--font-geist-mono, monospace))",
              fontSize: "0.72rem",
              letterSpacing: "0.14em",
              textTransform: "uppercase",
              color: "var(--color-fd-muted-foreground, rgba(255,255,255,0.58))",
            }}
          >
            Install in one command
          </span>

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "auto 1fr auto",
              alignItems: "stretch",
              border: "1px solid var(--color-fd-border, rgba(255,255,255,0.12))",
              background: "color-mix(in srgb, var(--color-fd-card, #111) 92%, transparent)",
            }}
          >
            <span
              style={{
                display: "grid",
                placeItems: "center",
                padding: "0 1rem",
                borderRight: "1px solid var(--color-fd-border, rgba(255,255,255,0.12))",
                fontFamily: "var(--fd-font-mono, var(--font-geist-mono, monospace))",
                fontSize: "1rem",
                color: "var(--color-fd-muted-foreground, rgba(255,255,255,0.58))",
              }}
            >
              &gt;
            </span>
            <code
              style={{
                display: "grid",
                alignItems: "center",
                padding: "0.95rem 1rem",
                textAlign: "left",
                fontFamily: "var(--fd-font-mono, var(--font-geist-mono, monospace))",
                fontSize: "clamp(0.82rem, 2vw, 1rem)",
                overflowX: "auto",
                whiteSpace: "nowrap",
              }}
            >
              {installCommand}
            </code>
            <button
              type="button"
              onClick={copyCommand}
              style={{
                border: 0,
                borderLeft: "1px solid var(--color-fd-border, rgba(255,255,255,0.12))",
                background: "transparent",
                color: "inherit",
                minWidth: 88,
                padding: "0 1rem",
                cursor: "pointer",
                fontFamily: "var(--fd-font-mono, var(--font-geist-mono, monospace))",
                fontSize: "0.72rem",
                letterSpacing: "0.14em",
                textTransform: "uppercase",
              }}
            >
              {copied ? "Copied" : "Copy"}
            </button>
          </div>
        </div>

        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            justifyContent: "center",
            alignItems: "center",
            gap: "1rem",
          }}
        >
          <Link
            to="/docs"
            style={{
              ...buttonBase,
              background: "var(--color-fd-foreground, #fff)",
              color: "var(--color-fd-background, #0b0b0c)",
            }}
          >
            Open Example Docs
          </Link>
          <a
            className="inline-flex h-full items-end gap-2 border-b border-dotted border-black/20 pb-0.5 font-mono uppercase tracking-[0.14em] text-[0.66rem] text-black/45 transition hover:text-black/70 dark:border-white/20 dark:text-white/45 dark:hover:text-white/70"
            href={referenceHref}
            target="_blank"
            rel="noreferrer"
            style={{
              textDecoration: "none",
            }}
          >
            <span>docs.farming-labs.dev</span>
            <span style={{ opacity: 0.55 }}>↗</span>
          </a>
        </div>

        <p
          className="font-mono uppercase tracking-tight text-black/30 dark:text-white/30"
          style={{
            margin: 0,
            color: "var(--color-fd-muted-foreground, rgba(255,255,255,0.58))",
            fontSize: "0.82rem",
          }}
        >
          // Start locally at <code>/docs</code>, then use the full reference when you need the
          broader map.
        </p>
      </section>
    </main>
  );
}
